- name: Setup local dev machine
  hosts: localhost
  connection: local

  tasks:
    - name: Add Homebrew taps
      homebrew_tap:
        name: "{{ taps }}"
        state: present
      when:
        - ansible_facts['os_family'] == "Darwin"
        - taps | length > 0

    - name: Install Homebrew packages
      homebrew:
        state: present
        name: "{{ packages }}"
      when:
        - ansible_facts['os_family'] == "Darwin"
        - packages | length > 0

    - name: Install packages
      homebrew_cask:
        name: "{{ casks }}"
        state: present
      when:
        - ansible_facts['os_family'] == "Darwin"
        - casks | length > 0
